"""
ABREngine — PyTorch vs ONNX Runtime parity validation (Python side)
===================================================================

Runs every golden fixture through:

    (a) the original PyTorch ActorCritic
    (b) the exported ONNX graph via onnxruntime (CPU EP)

and reports max absolute / relative deviation plus argmax agreement.

The JavaScript side of the same comparison lives in
``packages/abrengine/test/parity.test.ts`` and consumes the *same*
``export/fixtures/parity-fixtures.json``, so a three-way chain is covered:

    PyTorch  ->  ONNX (Python ORT)  ->  ONNX (Node onnxruntime-node)

Usage:
    python export/validate_parity.py
    python export/validate_parity.py --atol 1e-5 --value-atol 1e-4
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import onnxruntime as ort
import torch

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))
sys.path.insert(0, str(REPO_ROOT / "export"))

from model import S_INFO, S_LEN  # noqa: E402
from export_onnx import load_net  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--checkpoint", default=str(REPO_ROOT / "checkpoints" / "abrengine_final.pt")
    )
    ap.add_argument(
        "--model",
        default=str(
            REPO_ROOT / "packages" / "abrengine" / "models" / "ac3-controller.onnx"
        ),
    )
    ap.add_argument(
        "--fixtures",
        default=str(REPO_ROOT / "export" / "fixtures" / "parity-fixtures.json"),
    )
    ap.add_argument("--atol", type=float, default=1e-5, help="tolerance on probabilities")
    ap.add_argument(
        "--value-atol", type=float, default=1e-4, help="absolute tolerance on critic value"
    )
    ap.add_argument(
        "--value-rtol",
        type=float,
        default=1e-5,
        help=(
            "relative tolerance on critic value. The critic is unbounded, so a pure "
            "absolute tolerance is meaningless on the deliberately out-of-distribution "
            "fixtures where |V(s)| reaches ~2e5 and float32 ULP alone is ~1e-2."
        ),
    )
    args = ap.parse_args()

    data = json.loads(Path(args.fixtures).read_text())
    cases = data["cases"]
    states = np.array([c["state"] for c in cases], dtype=np.float32).reshape(
        -1, S_INFO, S_LEN
    )

    # --- PyTorch reference ------------------------------------------------
    net = load_net(Path(args.checkpoint))
    with torch.no_grad():
        t_probs, t_value = net(torch.from_numpy(states))
    t_probs = t_probs.numpy()
    t_value = t_value.numpy().reshape(-1)

    # --- Fixtures were generated by PyTorch: they must agree exactly -------
    f_probs = np.array([c["expected"]["actionProbs"] for c in cases], dtype=np.float32)
    fixture_drift = float(np.max(np.abs(t_probs - f_probs)))

    # --- ONNX Runtime -----------------------------------------------------
    sess = ort.InferenceSession(args.model, providers=["CPUExecutionProvider"])
    inp = sess.get_inputs()[0].name
    o_probs, o_value = sess.run(None, {inp: states})
    o_value = np.asarray(o_value).reshape(-1)

    # Also verify batch-size-1 execution gives identical results to batching,
    # because that is how the JS package actually calls the model.
    single = np.stack(
        [sess.run(None, {inp: states[i : i + 1]})[0][0] for i in range(len(states))]
    )
    batch_vs_single = float(np.max(np.abs(single - o_probs)))

    d_probs = np.abs(t_probs - o_probs)
    d_value = np.abs(t_value - o_value)
    rel = d_probs / np.maximum(np.abs(t_probs), 1e-12)
    rel_value = d_value / np.maximum(np.abs(t_value), 1e-12)
    value_budget = args.value_atol + args.value_rtol * np.abs(t_value)

    t_arg = t_probs.argmax(axis=1)
    o_arg = o_probs.argmax(axis=1)
    agree = int((t_arg == o_arg).sum())

    print(f"fixtures                 : {len(cases)}")
    print(f"fixture vs live PyTorch  : max |Δp| = {fixture_drift:.3e}")
    print(f"batch vs per-sample ONNX : max |Δp| = {batch_vs_single:.3e}")
    print(f"PyTorch vs ONNX probs    : max |Δ| = {d_probs.max():.3e}  "
          f"mean |Δ| = {d_probs.mean():.3e}  max rel = {rel.max():.3e}")
    print(f"PyTorch vs ONNX value    : max |Δ| = {d_value.max():.3e}  "
          f"mean |Δ| = {d_value.mean():.3e}  max rel = {rel_value.max():.3e}")
    print(f"argmax agreement         : {agree}/{len(cases)}")

    ok = True
    if d_probs.max() > args.atol:
        print(f"FAIL: probability deviation {d_probs.max():.3e} > atol {args.atol:.0e}")
        ok = False
    over = np.nonzero(d_value > value_budget)[0]
    if len(over):
        worst = over[np.argmax(d_value[over] - value_budget[over])]
        print(
            f"FAIL: critic value out of tolerance on {len(over)} case(s); worst "
            f"'{cases[worst]['id']}' |Δ|={d_value[worst]:.3e} "
            f"budget={value_budget[worst]:.3e}"
        )
        ok = False
    if agree != len(cases):
        bad = [cases[i]["id"] for i in np.nonzero(t_arg != o_arg)[0][:10]]
        print(f"FAIL: argmax disagreement on {len(cases)-agree} cases, e.g. {bad}")
        ok = False
    if fixture_drift > 0:
        print(f"FAIL: fixtures do not match the current checkpoint ({fixture_drift:.3e})")
        ok = False

    print("PASS" if ok else "FAILED")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
