/**
 * The parity test.
 * ================
 *
 * Runs every golden fixture generated by PyTorch (`export/make_fixtures.py`)
 * through the exported ONNX graph on the JavaScript runtime, and asserts the
 * outputs match.
 *
 * This is the test that justifies claiming the JS package runs "the same
 * controller" as the research code. If it fails, that claim is false.
 *
 * Tolerances:
 *   probabilities  — 1e-5 absolute. Observed max deviation is 7.7e-7.
 *   critic value   — 1e-4 absolute + 1e-5 relative. The critic is unbounded
 *                    (deliberately out-of-distribution fixtures reach |V| ≈ 2e5,
 *                    where one float32 ULP is already ~1.6e-2), so a purely
 *                    absolute tolerance would be meaningless there.
 *   argmax         — must agree on every single fixture. This is the one that
 *                    actually matters: it is the decision the player acts on.
 */

import { beforeAll, describe, expect, it } from 'vitest';

import { createSession, configureRuntime, resolveRuntime } from '../src/model/runtime.js';
import type { AbrInferenceSession } from '../src/types/config.js';
import { A_DIM, S_INFO, S_LEN } from '../src/model/manifest.js';
import { loadModelBytes, loadParityFixtures, type ParityFile } from './helpers.js';

const PROB_ATOL = 1e-5;
const VALUE_ATOL = 1e-4;
const VALUE_RTOL = 1e-5;

describe('PyTorch → ONNX → JavaScript parity', () => {
  let session: AbrInferenceSession;
  let fixtures: ParityFile;

  beforeAll(async () => {
    fixtures = loadParityFixtures();
    const rt = await resolveRuntime({ runtime: 'auto' });
    configureRuntime(rt, { wasmThreads: 1 });
    session = await createSession(rt, loadModelBytes(), { executionProviders: ['wasm'] });
  });

  it('fixture file matches the expected schema', () => {
    expect(fixtures.schema.stateShape).toEqual([S_INFO, S_LEN]);
    expect(fixtures.schema.aDim).toBe(A_DIM);
    expect(fixtures.cases.length).toBeGreaterThan(100);
    expect(fixtures.count).toBe(fixtures.cases.length);
  });

  it('reproduces PyTorch outputs on every fixture', async () => {
    let maxProbDelta = 0;
    let maxValueDelta = 0;
    let maxValueRel = 0;
    const argmaxMismatches: string[] = [];
    const valueOverBudget: string[] = [];

    for (const c of fixtures.cases) {
      expect(c.state.length).toBe(S_INFO * S_LEN);
      const out = await session.run(Float32Array.from(c.state));

      expect(out.actionProbs.length).toBe(A_DIM);

      for (let i = 0; i < A_DIM; i++) {
        const d = Math.abs(
          (out.actionProbs[i] as number) - (c.expected.actionProbs[i] as number),
        );
        if (d > maxProbDelta) maxProbDelta = d;
      }

      const dv = Math.abs(out.stateValue - c.expected.stateValue);
      const budget = VALUE_ATOL + VALUE_RTOL * Math.abs(c.expected.stateValue);
      if (dv > maxValueDelta) maxValueDelta = dv;
      const rel = dv / Math.max(Math.abs(c.expected.stateValue), 1e-12);
      if (rel > maxValueRel) maxValueRel = rel;
      if (dv > budget) valueOverBudget.push(`${c.id} (|Δ|=${dv}, budget=${budget})`);

      let argmax = 0;
      for (let i = 1; i < A_DIM; i++) {
        if ((out.actionProbs[i] as number) > (out.actionProbs[argmax] as number)) argmax = i;
      }
      if (argmax !== c.expected.action) {
        argmaxMismatches.push(`${c.id}: js=${argmax} torch=${c.expected.action}`);
      }
    }

    // Printed so a regression report carries the numbers, not just a pass/fail.
    console.log(
      `parity over ${fixtures.cases.length} fixtures: ` +
        `maxΔprob=${maxProbDelta.toExponential(3)} ` +
        `maxΔvalue=${maxValueDelta.toExponential(3)} ` +
        `maxRelValue=${maxValueRel.toExponential(3)}`,
    );

    expect(
      argmaxMismatches,
      `argmax disagreements: ${argmaxMismatches.slice(0, 5).join('; ')}`,
    ).toHaveLength(0);
    expect(
      valueOverBudget,
      `critic value out of tolerance: ${valueOverBudget.slice(0, 5).join('; ')}`,
    ).toHaveLength(0);
    expect(maxProbDelta).toBeLessThan(PROB_ATOL);
  });

  it('is deterministic — repeated runs of the same input agree exactly', async () => {
    const c = fixtures.cases[0]!;
    const a = await session.run(Float32Array.from(c.state));
    const b = await session.run(Float32Array.from(c.state));
    expect(Array.from(b.actionProbs)).toEqual(Array.from(a.actionProbs));
    expect(b.stateValue).toBe(a.stateValue);
  });

  it('rejects a state tensor of the wrong length', async () => {
    await expect(session.run(new Float32Array(10))).rejects.toThrow(/expected 48/);
  });
});
