/**
 * Port of `src/train.py::StateBuilder`.
 * =====================================
 *
 * This is the single place where player observations become the model's input
 * tensor. It is a *line-for-line* port: the row layout, the shift direction, the
 * normalisation divisors and the cold-start zero state all match the research
 * code. `test/state-builder.test.ts` checks it against fixtures generated by the
 * Python implementation.
 *
 * Reference (`src/train.py`):
 *
 * ```python
 * tp = (chunk_b * 8.0 / 1e6) / max(delay_s, 1e-6)
 * self.state[0, :-1] = self.state[0, 1:];  self.state[0, -1] = tp / THROUGHPUT_NORM
 * self.state[1, :-1] = self.state[1, 1:];  self.state[1, -1] = delay_s
 * for i in range(NUM_BITRATES): self.state[2, i] = next_cs[i] / CHUNK_NORM
 * self.state[3, -1] = buffer_s / BUFFER_NORM
 * self.state[4, -1] = remain   / NUM_CHUNKS
 * self.state[5, -1] = bitrate  / (NUM_BITRATES - 1)
 * ```
 *
 * Two behaviours are worth calling out because they are load-bearing:
 *
 * 1. **Rows 3, 4 and 5 are never shifted.** Only index `S_LEN-1` is written, and
 *    the model reads only that index. Indices 0..S_LEN-2 of those rows stay 0
 *    for the whole session. Zeroing them on every update would be wrong (it is
 *    not what training did) and so would shifting them.
 * 2. **Row 2 is written at indices 0..A_DIM-1 only.** Indices A_DIM..S_LEN-1
 *    stay 0 forever; the model slices `[:, 2, :A_DIM]`, so they are unused —
 *    but leaving them at 0 keeps the tensor byte-identical to training.
 */

import {
  A_DIM,
  BUFFER_NORM_SEC,
  CHUNK_NORM_BYTES,
  ROW,
  S_LEN,
  STATE_SIZE,
  THROUGHPUT_NORM,
  TOTAL_CHUNKS_NORM,
} from '../model/manifest.js';

/** Resolved normalisation constants. */
export interface StateNormalisation {
  bufferNormSec: number;
  chunkNormBytes: number;
  throughputNorm: number;
  totalChunksNorm: number;
}

/** One step of player-observed reality, already in research units. */
export interface StateStep {
  /** Transferred size of the segment that just completed, bytes. */
  segmentBytes: number;
  /** Download duration of that segment, seconds. */
  downloadSec: number;
  /**
   * Throughput, **Mbps**. Optional: when omitted it is derived exactly as the
   * research code does, `segmentBytes * 8 / 1e6 / max(downloadSec, 1e-6)`.
   */
  throughputMbps?: number;
  /** Forward buffer, seconds. */
  bufferSec: number;
  /** Segments left in the presentation. */
  remainingSegments: number;
  /**
   * Action index (0..A_DIM-1) of the rendition the completed segment was
   * downloaded at. This is the *model's* action space, not the player's ladder
   * index — the two are reconciled by `core/ladder.ts` before we get here.
   */
  lastActionIndex: number;
  /**
   * Next-segment size in bytes for each of the A_DIM action slots, in action
   * order. Length must be A_DIM; shorter arrays leave the remainder at 0.
   */
  nextSegmentBytesByAction: readonly number[];
}

const EPS = 1e-6;

export class StateBuilder {
  /** Row-major `[S_INFO][S_LEN]` buffer, shape-compatible with the ONNX input. */
  private readonly state = new Float32Array(STATE_SIZE);
  private readonly norm: StateNormalisation;
  private updates = 0;

  constructor(norm?: Partial<StateNormalisation>) {
    this.norm = {
      bufferNormSec: norm?.bufferNormSec ?? BUFFER_NORM_SEC,
      chunkNormBytes: norm?.chunkNormBytes ?? CHUNK_NORM_BYTES,
      throughputNorm: norm?.throughputNorm ?? THROUGHPUT_NORM,
      totalChunksNorm: norm?.totalChunksNorm ?? TOTAL_CHUNKS_NORM,
    };
  }

  /** Number of `update()` calls since the last `reset()`. */
  get updateCount(): number {
    return this.updates;
  }

  /** Back to the all-zero state the research code starts each episode from. */
  reset(): void {
    this.state.fill(0);
    this.updates = 0;
  }

  /** Apply one completed-segment observation. Mirrors `StateBuilder.update`. */
  update(step: StateStep): void {
    const { bufferNormSec, chunkNormBytes, throughputNorm, totalChunksNorm } = this.norm;

    const delaySec = step.downloadSec;
    const tpMbps =
      step.throughputMbps ?? (step.segmentBytes * 8.0) / 1e6 / Math.max(delaySec, EPS);

    // Row 0: throughput history — shift left, newest at the end.
    const tpBase = ROW.THROUGHPUT * S_LEN;
    for (let i = 0; i < S_LEN - 1; i++) this.state[tpBase + i] = this.state[tpBase + i + 1]!;
    this.state[tpBase + S_LEN - 1] = tpMbps / throughputNorm;

    // Row 1: download-time history — shift left, newest at the end.
    const dlBase = ROW.DOWNLOAD * S_LEN;
    for (let i = 0; i < S_LEN - 1; i++) this.state[dlBase + i] = this.state[dlBase + i + 1]!;
    this.state[dlBase + S_LEN - 1] = delaySec;

    // Row 2: next-segment sizes, one slot per action. Overwritten, not shifted.
    const csBase = ROW.CHUNK_SIZES * S_LEN;
    for (let i = 0; i < A_DIM; i++) {
      const v = step.nextSegmentBytesByAction[i];
      this.state[csBase + i] = (v ?? 0) / chunkNormBytes;
    }

    // Rows 3–5: scalars, written only at the last index.
    this.state[ROW.BUFFER * S_LEN + (S_LEN - 1)] = step.bufferSec / bufferNormSec;
    this.state[ROW.REMAINING * S_LEN + (S_LEN - 1)] = step.remainingSegments / totalChunksNorm;
    this.state[ROW.LAST_BITRATE * S_LEN + (S_LEN - 1)] = step.lastActionIndex / (A_DIM - 1);

    this.updates++;
  }

  /**
   * The current state tensor.
   *
   * Returns the internal buffer by default — the ONNX session copies it into a
   * tensor immediately, so this avoids one 192-byte allocation per decision.
   * Pass `true` when you need to retain it (telemetry does).
   */
  get(copy = false): Float32Array {
    return copy ? this.state.slice() : this.state;
  }

  /** Debug view: `[S_INFO][S_LEN]` nested arrays. */
  toRows(): number[][] {
    const rows: number[][] = [];
    for (let r = 0; r * S_LEN < STATE_SIZE; r++) {
      rows.push(Array.from(this.state.subarray(r * S_LEN, (r + 1) * S_LEN)));
    }
    return rows;
  }
}
